apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-ecommerce-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: site-ecommerce
  template:
    metadata:
      labels:
        app: site-ecommerce
    spec:
      containers:
      - name: site-ecommerce
        image: localhost:5000/todo-app
        ports:
        - containerPort: 3000
